### PR TITLE
Add .gitignore file + remove *.class files

### PR DESCRIPTION
**Pull request by enimiste**
Only java source code files should be pushed to this repository.
Maybe you should add this guideline to the contribution guide.

### CODE REVIEW

**Comment by jwheeler31** [comment]
I added a significant amount of files to `.gitignore` in pull request 92 (and ignored/removed `.class` files). I think it'll cover this PR.

**Comment by enimiste** [comment]
I checked your PR;
It consist of a lot of changes and an over defined `.gitignore` file that cover a lot files extensions that are out of java project context (`.iso, .tar`, ....).
### NB :
i think that PR should handle one atomic change and not many changes (New files, Code formatting, ....). Because a big PR may contains some stuff that should be merged and another one that shouldn't.

Thanks

**Comment by jwheeler31** [comment]
Even if I completely delete the `.gitignore`, this project needs a build system.

**Comment by enimiste** [comment]
I agree with you,
Because with the actual structure it is hard to work on it on IDE,

**Comment by jwheeler31** [comment]
I also understand the need to keep things simple per PR. That's the whole point. However, a single commit for each of the following is dumb:

VisualStudioCode, SublimeText, Eclipse, Windows, archives, Emacs, Microsoft Office temporary files, macOS, Java, JetBrains IDEs, Xcode, VisualStudio IDE, Maven, images

While it's easy to see this as overkill, I know that "beginners" (those for who this project is intended) will use anything they like and will most likely not know how to keep the repo clean. This is a precautionary measure. If you think that any of the above should be excluded, I'm all ears.

**Comment by jwheeler31** [comment]
By the way, @Kyle-Pu, was this ever addressed, or is this repository dead?

**Comment by marekpinto** [comment]
Hey @jwheeler31 ! Thanks for bringing this back up again. This repository is back under active moderation again. I've talked to Kyle, and we'll merge the pull request.

**Comment by jwheeler31** [comment]
Awesome!

A follow up - is there a desire to add a build system to this project? I _do not_ recommend Ant (does the job, but isn’t mainstream anymore). I haven’t used Gradle, but I’m decent with Maven.

The upsides of a build system are: simplified builds (new programers, see: compilation), simple IDE setup, use of other open source libraries, and ease of quality control (unit tests/code coverage/etc) amongst other things (this assumes that it sticks to one compiled language - I’d recommend that differing languages be separated into their own repos). The downside is that it requires a large PR as it requires reorganization of the project, which results in package name changes and imports.

**Pull request merged**
