### PR TITLE
Created GUI with Unit Test for the Geometry Area Formulas

### PR DESCRIPTION
**Pull request by scohen40**

### CODE REVIEW

**Comment by Kyle-P** [comment]
Hi @scohen40. Thanks for your contributions! We'll take a look into this soon and merge your work.

**Comment by Kyle-P** [comment]
Hi @scohen40. 

We'll begin to be more active here. @binoy-d would be better qualified to finalize this than me. I'll ask him for some help.

**Comment by scohen40** [comment]
Hi @Kyle-P and @binoy-d , any updates?

**Comment by marekpinto** [comment]
Hey @scohen40 ! This project is back under active moderation, I'll merge your pull request.

**Pull request merged**
